name: Build and test

on:
    # trigger on all commits to main
    #push:
    #    branches:
    #        - main
  
    # trigger on pull requests to main
    pull_request:
        branches:
            - main
  
    # trigger on request
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-20.04, macos-11, macos-14]
                python-version: ["3.8", "3.12"]
                exclude:
                    - os: macos-14
                      python-version: "3.8"

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip setuptools wheel pytest pytest-regtest

            - name: Build package and install through pip
              env:
                  ENABLE_CPP: ON
              run: |
                  pip install --verbose .

            - name: Run tests
              run: |
                  pytest -v

