name: Build and test

on:
  # trigger on all commits to main
  # NOTE: pushes to main should be protected by branch protection rules
  push:
    branches:
      - main

  # trigger on pull requests to main
  pull_request:
    branches:
      - main

  # trigger on request
  workflow_dispatch:

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            windows-latest,
            macos-latest,
            ubuntu-22.04,
            macos-13,
            macos-14,
          ]
        python-version: ["3.9", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: ğŸ“¦ Install uv
        uses: astral-sh/setup-uv@v5

      - name: ğŸ Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: ğŸ—ï¸ Build package and install through uv
        run: |
          uv pip install --upgrade pip
          uv pip install --verbose .[test] --config-settings=cmake.define.ENABLE_CPP=ON

      - name: ğŸ§ª Run tests
        run: |
          pytest -v
